services:
  db:
    image: pgvector/pgvector:0.8.0-pg15
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nornikel
      - POSTGRES_USER=docs
      - POSTGRES_PASSWORD=docs
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: